title: Emmanuel Kipkurui
logo: Data.png
description: I am a Data Analyst with experience in analyzing data using advanced Excel, SQL for data manipulation and interrogation, and Power BI for data visualization and developing business intelligence reports.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
